### ISSUE TITLE
Aegir CiviCRM integration

### ISSUE THREAD

**Issue by Shwele** [aegir-project/documentation#46] opened 2017-09-18 10:25 UTC
Hello guys,

Finally found some information with my struggles, hopefully you will reproduce the problem and offer piece of advice or if its general issue a proper fix in the future.

I have tried enabling CiviCRM under experimental and it has failed me so many times until I realized that enabling it makes my database, well, bit broken. Broken enough to stop Aegir from verifying configuration and functioning. It is causing PDO exception looking for templatedomain_0.civicrm_domain table that doesnt exist.

In attachment there is install log from Aegir and other one is where verify fails after you enable CiviCRM option.

Thanks in advance.
[install.txt](https://github.com/aegir-project/documentation/files/1310369/install.txt)
[verify_fail_full.txt](https://github.com/aegir-project/documentation/files/1310370/verify_fail_full.txt)

**Comment by helmo** [comment] 2017-09-18 11:55
The [issue queue on Drupal.org](https://www.drupal.org/project/issues/hosting_civicrm) is a better place for this question... 
But maybe @mlutfy has a quick answer?

**Comment by mlutfy** [comment] 2017-09-18 12:11
According to the install log, CiviCRM was not detected:

```
Calling hook drush_provision_civicrm_post_provision_install
Returned from hook drush_provision_civicrm_post_provision_install
```

Your verify log shows that the CiviCRM module is indeed in your platform:

```
Calling hook drush_provision_civicrm_pre_provision_verify
CiviCRM: found civicrm in packages
CiviCRM: civicrm is in /var/aegir/platforms/drupal-7.56/sites/all/modules/civicrm
```

Has anything changed between the install and the verify?

I don't see any obvious hint otherwise. You will have to debug by looking at `function _provision_civicrm_get_package_info()`:  
https://github.com/mlutfy/hosting_civicrm/blob/7.x-3.x/drush/provision_civicrm.inc#L364

**Comment by memtkmcc** [comment] 2017-09-18 12:12
CiviCRM is supported only if present/detected during the site installation. You can't add it to already installed site, at least not yet. It seems that is what you are trying to do?

**Comment by omega8cc** [comment] 2017-09-18 14:36
@Shwele It's a duplicate of https://www.drupal.org/node/2897465 you have already opened there some time ago. Please make sure you *install* the site on a platform with CiviCRM code already present and detected, after you have enabled this feature in Aegir. You can't add it once the site is already installed without CiviCRM.

**Closed as completed by omega8cc** 2017-09-18 14:36 UTC
Labels: duplicate

**Comment by omega8cc** [comment] 2017-09-18 14:40
@Shwele -- I can see that you are aware of this limitation, at least after reading the comments on the d.o. issue. Please follow up there. Thank you.

**Comment by omega8cc** [comment] 2017-09-18 14:43
@Shwele -- Last important detail: please don't use hostmaster platform to install hosted sites. You should create your own platform with all expected modules. You wrote on d.o.:

>> It was installed via aegir, location of module is /var/aegir/hostmaster-7.x-3.11/sites/all/modules/civicrm/

This is obviously wrong place to put civicrm.

**Comment by Shwele** [comment] 2017-09-21 07:53
Just rechecked so here is what I did in simple steps.

1. Turned on CiviCRM from hosting tab
2. Made new site test.website.org and created civicrm database in mysql called testwebsite_civi
3. Installed CiviCRM by going to test.website.org/sites/all/modules/civicrm/install/index.php and putting all needed inputs, installation is success
4. After that, I need to add permissions for Aegir to manage civicrm.settings.php and recursively for files/civicrm folder. User permissions are aegir:www-data
5. When I click to verify task and check if all is good, it fails, showing PDO exception as presented.

In the end it is corrupted so much that I cannot disable website and delete it. I have to delete it manually.

On the other note, I'm sorry for writing here too, but never got much response on drupal.org to call it success in response and ideas, saw that you were writing some issues here and that is why I wrote here as well. Ill use drupal.org for my issues in the future.

**Comment by memtkmcc** [comment] 2017-09-21 08:18
Please don't create separate database and don't install CiviCRM manually. It's not supported. Allow Aegir to install CiviCRM tables in the Drupal database and manage permissions. It should just work.

**Comment by Shwele** [comment] 2017-09-21 09:01
Ok, just found where was my flaw.

When creating platform, I always created it without civicrm present and added after I created platform itself.

Is there a way for platform to to populate those missing fields?

**Comment by memtkmcc** [comment] 2017-09-21 09:26
You don't need to have CiviCRM present when creating new platform. You just need to re-Verify the platform after adding any new code to it, and before installing new Drupal site.

**Comment by Shwele** [comment] 2017-09-21 09:42
Just tested it and it worked!
Now I have to be careful for old databases until we make new sites for those clients. Or there is just some set of tables that can be exported and imported?

Big thanks fellas. Its resolved and may be closed if you dont have anything to add regarding those set of tables.
